title: diego builds
description: >-
  Here my place where to store some good development idea and result.
baseurl: ""
url: ""
twitter_username: dtosato
github_username:  dtosato

# Build settings
theme: minima
plugins:
  - jekyll-feed

